spring:
  application:
    name: dss
  
  # MySQL Configuration (JPA)
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/dss_db_mysql}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:1234}
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  
  # MongoDB Configuration (Atlas Cloud)
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb+srv://vuthanhlam848:vuthanhlam848@cluster0.s9cdtme.mongodb.net/DSS?retryWrites=true&w=majority}
      database: ${MONGODB_DATABASE:DSS}

  # View Resolver (Thymeleaf)
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false

  # JSP View Resolver (alternative - uncomment to use JSP)
  # mvc:
  #   view:
  #     prefix: /WEB-INF/jsp/
  #     suffix: .jsp

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /

# Async Configuration
async:
  core-pool-size: 5
  max-pool-size: 20
  queue-capacity: 100
  thread-name-prefix: async-prediction-

# Model Service Configuration
model-service:
  base-url: ${MODEL_SERVICE_URL:http://localhost:8000}
  timeout: ${MODEL_SERVICE_TIMEOUT:30000}
  prediction-port: 8000
  analytics-port: 8001
  endpoints:
    sales-forecast: /api/forecast/sales
    churn-prediction: /api/predict/churn
    return-risk: /api/risk/return
    segmentation-analyze: /api/segmentation/analyze
    rfm-analysis: /api/rfm/analyze
    recommendations: /api/recommendations/generate
    market-basket: /api/market-basket/analyze
    anomaly-detect: /api/anomaly/detect
    invoice-audit: /api/audit/invoice
    policy-simulate: /api/policy/simulate
    optimal-threshold: /api/policy/optimal-threshold
    batch-evaluate: /api/policy/batch-evaluate

# Logging
logging:
  level:
    com.g5.dss: DEBUG
    org.springframework: INFO
    org.mongodb: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/dss-application.log

